version: '3'
services:

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_db_password
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost_db_password
      - MYSQL_DATABASE=ghost_production
    volumes:
      - ./data/dbdata:/var/lib/mysql

  ghost:
    image: ghost:alpine
    container_name: ghost
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json
   
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - ghost
    ports:
      - "<port>:80"
    volumes:
      - ./ssl/:/etc/letsencrypt/
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx/
